### ISSUE TITLE
>How to implement bloom effect now?

### ISSUE THREAD

**Issue by ajaxengine** [uber/luma.gl#1362]
> 
> 
> ![image](https://user-images.githubusercontent.com/42837853/47196264-48828780-d392-11e8-938c-9803ee2f352e.png)
> 
> recently , I saw this effect render lines for 3D effects ,when roads are rendered by corrdinate datas, red will exist constantly.
> If this kind of animation effects can achieved. I think it will use deck.gl and luma.gl。
> so ,if it can be come true.Any ideas about this question？need help！
> 
> online watting....

How to implement bloom effect now?

_Originally posted by @ajaxengine in https://github.com/uber/luma.gl/issues/759#issuecomment-587480122_

**Comment by ibgreen** [comment]
@ajaxengine I implemented the original batch of post processing effects in luma.gl. The bloom filter was actually one of the filters I really wanted to add. 

The principle is pretty simple, something like create a new texture that only has pixels with high intensity, apply a good blur filter to them, and add them back.

The problem was that creating a good blur filter (that blurs "a lot" and is also performance) is fairly involved and I had to move on to new things before I got it done.

A good blur filter is a great building block for many other effects so it would be great to see one added to luma.gl. It is quite an interesting yet isolated topic, a great place for someone to contribute.

**Comment by tsherif** [comment]
@ajaxengine Bloom can be implemented as a postprocessing pass in luma.gl. There's a good write up of the technique [here](https://learnopengl.com/Advanced-Lighting/Bloom) and a live demo I wrote using PicoGL [here](https://tsherif.github.io/picogl.js/examples/bloom.html). For some examples of how to set up post processing in luma.gl, see the [Persistence](https://luma.gl/examples/showcase/persistence/) or [DOF](https://luma.gl/examples/showcase/dof/) examples.

**Comment by ajaxengine** [comment]
@tsherif @ibgreen  thanks !

**Comment by vrman** [comment]
> @ajaxengine I implemented the original batch of post processing effects in luma.gl. The bloom filter was actually one of the filters I really wanted to add.
> 
> The principle is pretty simple, something like create a new texture that only has pixels with high intensity, apply a good blur filter to them, and add them back.
> 
> The problem was that creating a good blur filter (that blurs "a lot" and is also performant) is fairly involved and I had to move on to new things before I got it done.
> 
> A good blur filter is a great building block for many other effects so it would be great to see one added to luma.gl. It is quite an interesting yet isolated topic, a great place for someone to contribute.

is this possible to make an example to how do this ?
thanks

**Comment by LouisH98** [comment]
It's a shame this is still not possible/documented. Even a simple multi-pass effect example would be great to see!
